output_dir: 'hp_stats'
num_trials: 15
num_folds: 5
hyperparameters:
  edge_pred_loss_scale:
    path: 'loss_func_parameters.edge_pred_loss_scale'
    type: 'float'
    min: 1.0e-3
    max: 1.0e-1
    log: True
  global_mass_loss_scale:
    path: 'loss_func_parameters.global_mass_loss_scale'
    type: 'float'
    min: 1.0e-11
    max: 1.0e-9
    log: True
