output_dir: 'hp_stats'
num_trials: 20
num_folds: 5
hyperparameters:
  # edge_loss_weight:
  #   path: 'loss_func_parameters.edge_loss_weight'
  #   type: 'float'
  #   min: 0.5
  #   max: 1.5
  #   log: True
  global_mass_loss_weight:
    path: 'loss_func_parameters.global_mass_loss_weight'
    type: 'float'
    min: 1.0e-3
    max: 1.0e-1
    log: True
