dataset_parameters:
  storage_mode: 'memory'                                # 'memory' or 'disk'
  root_dir: 'data/datasets'
  nodes_shp_file: 'New_Geometry/cell_centers_with_ele.shp'
  edges_shp_file: 'New_Geometry/links_with_slope.shp'
  features_stats_file: 'features_stats.yaml'

  previous_timesteps: 1
  normalize: True
  timestep_interval: 900                                 # Interval between timesteps in seconds
  spin_up_time: 259200                                    # Spin up time in seconds; Can be defined per Run ID
  # spin_up_time:
  #   38: 259200
  #   39: 259200
  #   40: 259200
  #   41: 259200
  #   default: 129600
  time_from_peak: 7200                                 # Time from peak in seconds; This is used to determine the number of timesteps to consider from the peak
  inflow_boundary_nodes:
  - 1248
  outflow_boundary_nodes:
  - 1253
  - 1129

  training:
    dataset_summary_file: 'train.csv'
    event_stats_file: 'train_event_stats.yaml'

  testing:
    dataset_summary_file: 'test.csv'
    event_stats_file: 'test_event_stats.yaml'

training_parameters:
  log_path             : 'autoregressive/logs/auto1_train.log'                                # Path to save training logs
  model_dir            : 'autoregressive/model'                      # Directory to save trained models
  stats_dir            : 'autoregressive/train'                    # Directory to save training statistics
  checkpoint_path      : null                                # Path to load a pre-trained model; If None, no pre-trained model is loaded
  num_epochs           : 100                                # Number of epochs
  num_epochs_dyn_loss  : 0                                  # Number of epochs to determine loss scaling ratios dynamically; Usually 10 epochs is sufficient
  # num_epochs           : 10                                # Number of epochs
  # num_epochs_dyn_loss  : 10                                  # Number of epochs to determine loss scaling ratios dynamically; Usually 10 epochs is sufficient
  batch_size           : 32                                  # Batch size
  learning_rate        : 0.0001 # Auto 1                              # Learning rate
  # learning_rate        : 0.00007   # Auto 2                             # Learning rate
  # learning_rate        : 4.9e-5   # Auto 3                             # Learning rate
  # learning_rate        : 3.43e-5   # Auto 4                             # Learning rate
  # learning_rate        : 2.4e-5   # Auto 5-6                             # Learning rate
  # learning_rate        : 1.18e-5   # Auto 7-8                             # Learning rate
  # learning_rate        : 5.78e-6   # Auto 9-10                             # Learning rate
  adam_weight_decay    : 0                                   # Weight decay
  gradient_clip_value : 0.5                                  # Gradient clipping value; If None, no gradient clipping is applied
  early_stopping_patience: 15                                 # Early stopping patience for autoregressive training
  val_split_percent  : 0.1                                    # Percentage of validation split for autoregressive training

  autoregressive:
    enabled            : True                                # Use autoregressive training
    init_num_timesteps : 1                                   # Initial number of timesteps for autoregressive training
    total_num_timesteps: 1                                   # Total number of timesteps for autoregressive training
    max_curriculum_epochs: 100                                # Maximum number of curriculum steps
    learning_rate_decay  : 0.7                               # Learning rate decay factor after each curriculum step

loss_func_parameters:
  node_loss: 'mse'                                         # Loss function for node features. Options: 'mse', 'mae', 'huber'
  edge_loss: 'mse'                                         # Loss function for edge features. Options: 'mse', 'mae', 'huber'
  node_loss_weight: 1.0                                      # Importance weight for node prediction loss. Applied after scaling.
  edge_pred_loss_scale: 1.48                              # Value used to scale edge prediction loss; This is used as an initial value when using dynamic loss scaling
  edge_loss_weight: 1.0                                      # Importance weight for edge prediction loss. Applied after scaling.
  use_global_mass_loss: False                                # Use global mass conservation in loss function
  global_mass_loss_scale: 1.0e-5                             # Value used to scale global mass conservation loss; This is used as an initial value when using dynamic loss scaling
  global_mass_loss_weight: 1.0                               # Importance weight for global mass conservation loss. Applied after scaling.
  use_local_mass_loss: False                                 # Use local mass conservation in loss function
  local_mass_loss_scale: 1.0e-5                              # Value used to scale local mass conservation loss; This is used as an initial value when using dynamic loss scaling
  local_mass_loss_weight: 1.0                                # Importance weight for local mass conservation loss. Applied after scaling.

  huber:
    delta: 0.15                                             # Delta parameter for Huber loss function.

testing_parameters:
  log_path: 'autoregressive/logs/auto1_test.log'                                        # Path to save testing logs
  output_dir: 'autoregressive/test'                           # Directory to save testing results
  rollout_start: 0                                      # Start timestep for the test rollout
  rollout_timesteps: null                               # Number of timesteps for the test rollout (30 seconds each)

model_parameters:
  GCN:
    hidden_features: 32
    num_layers: 2
    activation: 'relu'
    residual: False
    encoder_layers: 2
    encoder_activation: 'relu'
    decoder_layers: 2
    decoder_activation: 'relu'

  GAT:
    hidden_features: 32
    use_edge_features: False
    num_layers: 2
    activation: 'relu'
    residual: False
    num_heads: 1
    dropout: 0.0
    add_self_loops: True
    negative_slope: 0.2
    attn_bias: True
    attn_residual: True
    encoder_layers: 2
    encoder_activation: 'relu'
    decoder_layers: 2
    decoder_activation: 'relu'

  NodeEdgeGNN:
    hidden_features: 64
    num_layers: 3
    activation: 'relu'
    mlp_layers: 3
    encoder_layers: 3
    encoder_activation: 'relu'
    decoder_layers: 3
    decoder_activation: 'relu'

  NodeEdgeGNNAttn:
    hidden_features: 16
    num_layers: 2
    activation: 'relu'
    residual: True
    dropout: 0.0
    negative_slope: 0.2
    attn_mlp_layers: 2
    encoder_layers: 2
    encoder_activation: 'relu'
    decoder_layers: 2
    decoder_activation: 'relu'

  NodeGNNAttn:
    hidden_features: 8
    num_layers: 2
    activation: 'relu'
    residual: True
    dropout: 0.0
    negative_slope: 0.2
    attn_mlp_layers: 2
    encoder_layers: 2
    encoder_activation: 'relu'
    decoder_layers: 2
    decoder_activation: 'relu'

  EdgeGNNAttn:
    hidden_features: 8
    num_layers: 2
    activation: 'relu'
    residual: True
    dropout: 0.0
    negative_slope: 0.2
    attn_mlp_layers: 2
    encoder_layers: 2
    encoder_activation: 'relu'
    decoder_layers: 2
    decoder_activation: 'relu'

  HydroGraphNet:
    hidden_features: 128
    num_layers: 15
    mlp_layers: 3
    activation: 'relu'
    encoder_layers: 3
    encoder_activation: 'relu'
    decoder_layers: 3
    decoder_activation: 'relu'

