dataset_parameters:
  storage_mode: 'memory'                                # 'memory' or 'disk'
  root_dir: 'data/datasets'
  nodes_shp_file: 'Geometry/updated_cell_centers.shp'
  edges_shp_file: 'Geometry/links.shp'
  features_stats_file: 'features_stats.yaml'

  previous_timesteps: 6
  normalize: True
  timestep_interval: 30                                 # Interval between timesteps in seconds (must be a multiple of 30)
  spin_up_timesteps: 2880                               # Number of timesteps to spin up the model (30 seconds each)
  timesteps_from_peak: null                             # Number of timesteps to consider from the peak (30 seconds each)
  inflow_boundary_nodes:
  - 1248
  outflow_boundary_nodes:
  - 1253
  - 1129

  training:
    dataset_summary_file: 'train.csv'
    event_stats_file: 'train_event_stats.yaml'

  testing:
    dataset_summary_file: 'test.csv'
    event_stats_file: 'test_event_stats.yaml'

training_parameters:
  log_path             : null                                # Path to save training logs
  model_dir            : 'saved_models'                      # Directory to save trained models
  stats_dir            : 'training_stats'                    # Directory to save training statistics
  num_epochs           : 100                                 # Number of epochs
  batch_size           : 128                                 # Batch size
  learning_rate        : 0.0001                              # Learning rate
  weight_decay         : 0                                   # Weight decay

loss_func_parameters:
  edge_pred_loss_percent: 0.5                                # Percentage of edge prediction loss in total loss
  use_global_mass_loss: False                                # Use global mass conservation in loss function
  use_local_mass_loss: False                                 # Use local mass conservation in loss function
  global_mass_loss_percent: 0.00008                          # Percentage of global mass conservation loss in total loss
  local_mass_loss_percent: 0.00008                           # Percentage of local mass conservation loss in total loss

testing_parameters:
  log_path: null                                        # Path to save testing logs
  output_dir: 'saved_metrics'                           # Directory to save testing results
  rollout_start: 0                                      # Start timestep for the test rollout
  rollout_timesteps: null                               # Number of timesteps for the test rollout (30 seconds each)

model_parameters:
  GCN:
    hidden_features: 32
    num_layers: 2
    activation: 'prelu'
    residual: True
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'

  GAT:
    hidden_features: 32
    use_edge_features: False
    num_layers: 2
    activation: 'prelu'
    residual: True
    num_heads: 1
    dropout: 0.0
    add_self_loops: True
    negative_slope: 0.2
    attn_bias: True
    attn_residual: True
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'

  NodeEdgeGNN:
    hidden_features: 32
    num_layers: 2
    activation: 'prelu'
    residual: True
    mlp_layers: 2
    enforce_flipped_edge_attr: False
    encoder_layers: 2
    encoder_activation: 'prelu'
    decoder_layers: 2
    decoder_activation: 'prelu'
